version: '3.8'

services:
  mi-app:
    build: .
    image: mi_trabajo_individual
    ports:
      - "8080:8080"
    networks:
      - red-trabajo

  servicio-vm:
    image: javillour/servicio-tt1:amd64
    networks:
      - red-trabajo

networks:
  red-trabajo: